name: foodee
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.5
  http: ^1.2.2
  shimmer: ^3.0.0
  glass: ^2.0.0+1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  get_storage: ^2.1.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.14.0
  device_preview: ^1.2.0
  otp_text_field: ^1.1.3
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  country_picker: ^2.0.26
  dio: ^5.6.0
  velocity_x: ^4.2.1
  weather: ^3.1.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - assets/anime/
    - assets/icons/
    - assets/foodly/
    - assets/foodly/banners/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
